apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  namespace: mesh-two
  name: mesh-two
spec:
  proxy:
    accessLogging:
      file:
        name: /dev/stdout
  cluster:
    name: backend-cluster
    network: mesh-two-network
  security:
    trust:
      domain: mesh-two.local
  version: v2.1
  runtime:
    defaults:
      container:
        imagePullPolicy: Always
  gateways:
    openshiftRoute:
      enabled: false
    additionalEgress:
      mesh-one-egress:
        enabled: true
        requestedNetworkView:
        - mesh-one-network
        routerMode: sni-dnat
        service:
          metadata:
            labels:
              federation.maistra.io/egress-for: mesh-one-egress
          ports:
          - port: 15443
            name: tls
          - port: 8188
            name: http-discovery
    additionalIngress:
      mesh-one-ingress:
        enabled: true
        routerMode: sni-dnat
        service:
          type: ClusterIP # or LoadBalancer or NodePort, LB in this case must be externally provisioned
          metadata:
            labels:
              federation.maistra.io/ingress-for: mesh-one-ingress
          ports:
          - port: 15443
            name: tls
          - port: 8188
            name: https-discovery
  tracing:
    sampling: 10000
    type: Jaeger
  policy:
    type: Istiod
  addons:
    grafana:
      enabled: true
    jaeger:
      install:
        storage:
          type: Memory
    kiali:
      enabled: true
    prometheus:
      enabled: true
  telemetry:
    type: Istiod

