apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  product: openshift-servicemesh
  kind: controlplane-mesh-two
  master: kube-kustomize

resources:
  - namespace.yaml
  - controlplane.yaml
  - member-roll.yaml
  - servicemesh-membership.yaml
