---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: distributed-tracing-operator
  namespace: openshift-distributed-tracing
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    olm.operatorGroup: distributed-tracing-operator
  name: distributed-tracing-operator
  namespace: openshift-distributed-tracing
spec:
  channel: "stable"
  installPlanApproval: "Automatic"
  source: "redhat-operators"
  sourceNamespace: "openshift-marketplace"
  name: "jaeger-product"
