apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  io.openshift.operators/cluster-wide: 'true'
  io.openshift.servicemesh/flavor: 'redhat'

commonLabels:
  app: openshift-servicemesh
  kind: operator
  master: kube-kustomize

resources:
  - namespace.yaml
  - kiali-subscription.yaml
  - distributed-tracing-subscription.yaml
  - istio-subscription.yaml
