---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: istio-demo-app-frontend-image
spec:
  type: image
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/istio-demo/demo-app-frontend
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: k8s-demo-app-github-repo-v1
spec:
  type: git
  params:
  - name: url
    value: https://github.com/mcaimi/k8s-demo-app
  - name: revision
    value: master
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: k8s-demo-app-github-repo-v2
spec:
  type: git
  params:
  - name: url
    value: https://github.com/mcaimi/servicemesh-demo
  - name: revision
    value: main
