---
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: container-build-run-
spec:
  pipelineRef:
    name: container-build-pipeline
  resources:
  - name: k8s-demo-app-github-repo
    resourceRef:
      name: k8s-demo-app-github-repo-v1
  - name: output-runnable-image
    resourceRef:
      name: istio-demo-app-frontend-image
  params:
    - name: dockerfilePath
      value: "src/main/docker"
    - name: dockerTag
      value: "v1"
  workspaces:
  - name: quarkus-maven-repo
    persistentVolumeClaim:
      claimName: build-pvc
