bases:
  - ../common
namespace: istio-demo
namePrefix: frontend-
nameSuffix: "-v2"
commonLabels:
  app: k8s-quarkus-app
  version: v2
commonAnnotations:
  deployedBy: "oc-kustomize"
  chain: "tekton-pipeline"
  environment: "istio-demo"
patchesStrategicMerge:
- mem-sizing.yaml
secretGenerator:
- name: quarkus-init-secret
  literals:
  - postgres_app_user=prod_user
  - postgres_app_db=prod_db
  - postgres_app_user_password=hibernate
  - db_driver=postgresql
  - db_hostname=backend-postgres-service-v1-community
  - db_port=5432
  - orm_log=true
  - default_schema=prod_schema
  - db_generation=none
  - hibernate_load_file=no-file
  - jdbc_max_size=8
  - jdbc_min_size=2
  - flyway_migrate_at_start=true
  - flyway_baseline_version=1.0.0
  - flyway_baseline_description=Prod_Initial
  - flyway_connection_retries=300
  - flyway_migration_table=prod_history
  - flyway_migrations_location=db/migrations/prod
  - flyway_baseline_on_migrate=true
images:
- name: java-runner
  newName: image-registry.openshift-image-registry.svc:5000/istio-demo/demo-app-frontend
  newTag: v2
